# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check Build, Execution, Deployment → Compiler → Android Compiler.
# (If you need to modify these values, you can edit the local.properties file instead,
# but you should avoid modifying this file manually.)
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/guide/in-depth/android_build#configuring-your-build-environment
#
# Specifies the JDK version to use when compiling project source code.
# This option is ignored on Windows.
# This option is also ignored if Gradle is configured to use a different Java home.
jdk.version=11
# The version of Android SDK to compile your project against.
# This actually sets a property to allow the build to know which SDK version
# expectations set by compileSdkVersion in /app/build.gradle.
android.compileSdkVersion=33
# Deprecated. Use compileSdkVersion instead.
android.buildToolsVersion=33.0.0
# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include transitive dependencies'
# resources. Enabling this property is useful if you want to build a library and want to
# keep your library's public API clean from transitive dependencies.
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
